config/routes.rb
Rails.application.routes.draw do
  resources :camps
  resources :cities
  resources :regions
  resources :countries

  get 'regions/:country_id/' , to: 'regions#index'
  get 'cities/:region_id/' , to: 'regions#index'

  get 'camps/:country_id', to: 'camps#index'
  get 'camps/:region_id', to: 'camps#index'
  get 'camps/"city_id', to: 'camps#index'
  root 'camps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/camp.rb
class Camp < ApplicationRecord
  belongs_to :city
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  # GET /camps
  # GET /camps.json
  def index
    if params[:city_id]
      @camps = City.find(params[:city_id]).camps.
          sort_by { |c| [c.city.region.country.name, c.city.region.name, c.city.name, c.name] }
    elsif params[:region_id]
      @camps = Camp.find_by_sql('SELECT camps.* FROM regions
	                                LEFT JOIN cities on cities.region_id = regions.id
                                  INNER JOIN camps on camps.city_id = cities.id
                                  WHERE regions.id =' + params[:region_id]).
                                  sort_by { |c| [c.city.region.country.name, c.city.region.name, c.city.name, c.name] }

=begin
      @camps = Region.where(region_id: params[:region_id]).left_joins(:cities).left_joins(:regions).select(:camp).jo
      region_id = params[:region_id].to_i
      region = Region.find(region_id)
      camps = []
      region.cities.each {|city|
        camps.append city.camps
      }
      @camps = camps
=end
    elsif params[:country_id]

      @camps = Camp.find_by_sql('SELECT camps.* FROM countries
                                  LEFT JOIN regions on regions.country_id = countries.id
                                  LEFT JOIN cities on cities.region_id = regions.id
                                  INNER JOIN camps on camps.city_id = cities.id
                                  WHERE countries.id=' + params[:country_id]).
                                  sort_by { |c| [c.city.region.country.name, c.city.region.name, c.city.name, c.name] }



    else
      @camps = Camp.all.sort_by { |c| [c.city.region.country.name, c.city.region.name, c.city.name, c.name] }
    end
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @camp = Camp.new
    @cities = City.all
  end

  # GET /camps/1/edit
  def edit
    @cities = City.all
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Запись успешно создана!' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Запись успешно обновлена!' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Запись успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:name, :description, :city_id)
    end
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_form.html.erb
    <%= form_with(model: camp, local: true) do |form| %>
      <% if camp.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(camp.errors.count, "error") %> К сожаление, сохранить записиь не удалось, попробуйте ещё:</h2>

          <ul>
          <% camp.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :"Название" %>
        <%= form.text_field :name, id: :camp_name, :required=>"",:class =>"form-control"%>
      </div>
      <div class="field">
        <%= form.label :"Описание"%>
        <%= form.text_area :description, id: :camp_description,:required=>"", :class =>"form-control", :resize => 'none'%>
      </div>
      <div class="field">
        <%= form.label :"Ближайший город" %>
        <%= form.collection_select :city_id, cities, :id, :name ,{}, { :class =>"form-control"} %>
      </div>
      </br>
      <div class="actions" align="right">
        <%= form.submit :"Готово" %>
      </div>
    <% end %>

app/views/camps/edit.html.erb
  <h1>Редактирование записи о турбазе</h1>



    <%= render partial: 'form', :locals => {:camp => @camp, :cities => @cities } %>

    <%= link_to 'Показать', camp: @camp  %> |
    <%= link_to 'Назад', camps_path %>

app/views/camps/index.html.erb
<p id="notice"><%= notice %></p>

  <h1>Список турбаз</h1>

  <div align="right">
    <%= link_to 'Добавить новую турбазу', new_camp_path%> <br>
  </div>
  <%= render partial: 'application/location_select'%>
  <table class="table camps-table">
    <thead>
      <tr>
        <th>id</th>
        <th>Страна</th>
        <th>Регион</th>
        <th>Город</th>
        <th>Название</th>
        <th>Описание</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @camps.each do |camp| %>
        <tr>

          <td><%= camp.id%></td>
          <td><%= camp.city.region.country.name %></td>
          <td><%= camp.city.region.name %></td>
          <td><%= camp.city.name %></td>
          <td><%= camp.name %></td>
          <td><%= camp.description %></td>
          <td><%= link_to 'Подробнее', camp %></td>
          <td><%= link_to 'Редактировать', edit_camp_path(camp) %></td>
          <td><%= link_to 'Удалить', camp, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить '+ camp.name + '?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'Добавить новую турбазу', new_camp_path %> <br>

app/views/camps/new.html.erb
  <h1>Создание новой записи о  турбазе</h1>

    <%= render partial:'form', :locals => {camp: @camp, cities: @cities}%>
    <%= link_to 'Назад', camps_path %>

app/views/camps/show.html.erb
  <p id="notice"><%= notice %></p>

  <h1></h1>

    <div class="col-md-6">
      <p>
        <strong>Название:</strong>
        <%= @camp.name %>
      </p>


      <p>
        <strong>Описание:</strong> </br>
        <%= @camp.description %>
      </p>



      <p>
        <strong>Город:</strong>
        <%= @camp.city.name %>
      </p>


    <%= link_to 'Редактировать', edit_camp_path(@camp) %> |
    <%= link_to 'Назад', camps_path %>

  </div>