config/routes.rb
Rails.application.routes.draw do
  resources :camps
  resources :cities
  resources :regions
  resources :countries

  get 'regions/:country_id/' , to: 'regions#index'
  get 'cities/:region_id/' , to: 'regions#index'

  get 'camps/:country_id', to: 'camps#index'
  get 'camps/:region_id', to: 'camps#index'
  get 'camps/"city_id', to: 'camps#index'
  root 'camps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :camps, :dependent => :delete_all
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    if params[:region_id]
      @cities = Region.find(params[:region_id]).cities
    else
      @cities = City.all
    end

  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @regions = Region.all
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
    @regions = Region.all
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'Запись успешно создана' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'Запись успешно обновлена!' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'Запись успешно удалена!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :region_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> К сожаление, сохранить записиь не удалось, попробуйте ещё::</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label "Название" %>
    <%= form.text_field :name, id: :city_name, :required=>"", :class =>"form-control" %>
  </div>

  <div class="field">
    <%= form.label "Регион" %>
    <%= form.collection_select :region_id, regions, :id, :name ,{}, {:class =>"form-control"}%>
    </br>
  </div>

  <div class="actions" align="right">
    <%= form.submit :"Готово" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
  <h1>Редактирование записи о городе</h1>


    <%= render partial: 'form', locals: {city: @city, regions: @regions}%>



    <%= link_to 'Показать', @city %> |
    <%= link_to 'Назад', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>


  <h1>Список городов</h1>

  <table class = "table">
    <thead>
      <tr>
        <th>Регион</th>
        <th>Город</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cities.each do |city| %>
        <tr>
          <td><%= city.region.name %></td>
          <td><%= city.name %></td>
          <td><%= link_to 'Подробнее', city %></td>
          <td><%= link_to 'Редактировать', edit_city_path(city) %></td>
          <td><%= link_to 'Удалить', city, method: :delete, data: { confirm: "Вы уверены?
Удаление данной записи повлечёт за собой удаление всех связанных записей (городов, турбаз) "} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить город', new_city_path %>

app/views/cities/new.html.erb
  <h1>Создание новой записи о городе</h1>
  <div class="row">
    <%= render partial: 'form', locals: {city: @city, regions: @regions}%>
  </div>
  <div class="row">
    <%= link_to 'Назад', cities_path %>
  </div>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

  <p>
    <strong>Название:</strong>
    <%= @city.name %>
  </p>

  <p>
    <strong>Регион:</strong>
    <%= @city.region.name %>
  </p>

  <%= link_to 'Редактировать', edit_city_path(@city) %> |
  <%= link_to 'Назад', cities_path %>