config/routes.rb
Rails.application.routes.draw do
  resources :camps
  resources :cities
  resources :regions
  resources :countries

  get 'regions/:country_id/' , to: 'regions#index'
  get 'cities/:region_id/' , to: 'regions#index'

  get 'camps/:country_id', to: 'camps#index'
  get 'camps/:region_id', to: 'camps#index'
  get 'camps/"city_id', to: 'camps#index'
  root 'camps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  has_many :cities, :dependent => :delete_all
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    if params[:country_id]
      @regions = Country.find(params[:country_id]).regions
    else
      @regions = Region.all
    end
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @countries = Country.all
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
    @countries = Country.all
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Запись успешно создана!' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Запись успешно обновлена!' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Запись успешно удалена!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :country_id)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region, local: true) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> К сожаление, сохранить записиь не удалось, попробуйте ещё::</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Название" %>
    <%= form.text_field :name, id: :region_name, :required=>"", :class =>"form-control" %>
  </div>

  <div class="field">
    <%= form.label "Страна" %>
    <%= form.collection_select :country_id, countries, :id, :name, {}, {:class =>"form-control"}%>
  </div>
  </br>
  <div class="actions" align="right">
    <%= form.submit :"Готово" %>
  </div>
<% end %>

app/views/regions/edit.html.erb
  <h1>Редактирование записи о регионе</h1>

    <%= render partial: 'form', locals: {region: @region, countries: @countries }%>

    <%= link_to 'Показать', @region %> |
    <%= link_to 'Назад', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>


  <h1>Список регионов</h1>

  <table class = "table">
    <thead>
      <tr>
        <th>Страна</th>
        <th>Регион</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @regions.each do |region| %>
        <tr>
          <td><%= region.country.name %></td>
          <td><%= region.name %></td>
          <td><%= link_to 'Подробнее', region %></td>
          <td><%= link_to 'Редактировать', edit_region_path(region) %></td>
          <td><%= link_to 'Удалить', region, method: :delete, data: { confirm: "Вы уверены?
Удаление данной записи повлечёт за собой удаление всех связанных записей ( турбаз)" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить Регион', new_region_path %>

app/views/regions/new.html.erb
<h1>Создание новой записи о регионе</h1>

    <%= render partial: 'form', locals: {region: @region, countries: @countries }%>

    <%= link_to 'Назад', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @region.name %>
</p>

<p>
  <strong>Страна:</strong>
  <%= @region.country.name %>
</p>

<%= link_to 'Редактировать', edit_region_path(@region) %> |
<%= link_to 'Назад', regions_path %>