config/routes.rb
Rails.application.routes.draw do
  resources :camps
  resources :cities
  resources :regions
  resources :countries

  get 'regions/:country_id/' , to: 'regions#index'
  get 'cities/:region_id/' , to: 'regions#index'

  get 'camps/:country_id', to: 'camps#index'
  get 'camps/:region_id', to: 'camps#index'
  get 'camps/"city_id', to: 'camps#index'
  root 'camps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_head_menu.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
    <div class="head-menu-header">
          <div class="row">
              <div class="col-md-12" align="center">
                  <h1> Турбазу в каждый дом</h1>
              </div>
          </div>
          <div class="row" >
              <div class="col-md-12" align="center"> <!-- TODO: Расстянуть группу кнопок -->
                  <div class="btn-group-justified head-menu-buttons ">
                      <a href= <%=camps_path%> role="button" class="btn btn-primary">Список турбаз</a>
                      <!-- Сделать переход -->
                      <a href=<%=countries_path%> role="button" class="btn btn-primary">Страны</a>
                      <a href=<%=regions_path%> role="button" class="btn btn-primary">Регионы</a>
                      <a href=<%=cities_path%> role="button" class="btn btn-primary">Города</a>
                  </div>
              </div>
          </div>
    </div>
</body>
</html>

app/views/application/_location_select.erb
    <div class="location-select">

      <table class="table-striped">
        <tr class="row">
          <td class="col-sm">Страна</td>
          <td class="col-sm">Регион</td>
          <td class="col-sm">Город</td>
        </tr>
        <tr class="row">
          <td class="col-sm">
            <select class="location-select-country">
            </select>
            ->
          </td>
          <td class="col-sm">
            <select class="location-select-region">
            </select>
            ->
          </td>
          <td class="col-sm">
            <select class="location-select-city">
            </select>
          </td>
        </tr>
      </table>
    </div>